server {
    listen 80;

    # ۱. مسیردهی به کانتینر فرانت‌اند
    location / {
        proxy_pass http://frontend:80;
    }

    # ۲. مسیردهی به کانتینر بک‌اند (API)
    location /api/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ۳. سرو کردن مستقیم فایل‌های سنگین مدیا (عکس و آهنگ)
    location /media/ {
        alias /media/;
    }
}
